spring.application.name=Recovery-User-Api
spring.datasource.url=jdbc:mysql://localhost:3306/recoverymicroservice
spring.datasource.username=devJPA
spring.datasource.password=NBCC1234!
spring.jpa.hibernate.ddl-auto=update
server.port=8083
logging.level.root=INFO
logging.level.nbcc=debug
logging.file.name=logs/user-rest-api.log
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
