spring.application.name=Recovery-Auth
spring.datasource.url=jdbc:mysql://localhost:3306/recoverymicroservice
spring.datasource.username=devJPA
spring.datasource.password=NBCC1234!
spring.jpa.hibernate.ddl-auto=update
server.port=8082
logging.level.root=INFO
logging.level.nbcc=debug
logging.file.name=logs/auth-rest-api.log
token.timeout=3600
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
